
services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - .:/import 
    environment:
      NEO4J_AUTH: ${NEO4J_USER}/${NEO4J_PASSWORD}

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - neo4j
      - postgres

volumes:
  neo4j_data:
  postgres_data: